name: 📌 External Resources Proposal
description: Fill out this form to provide information about the external resource to be referenced
title: "External Resources Proposal"
labels: ["resource"]
body:
  - type: markdown
    attributes:
      value: |
        ## Supplier name
  - type: input
    attributes:
      label: The name of the company that provides the resource
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        <br>

        ## Resources types
  - type: dropdown
    attributes:
      label: Select the types of products or services you are proposing (multiple options can be selected)
      multiple: true
      options:
        - Reader plugins
        - Card extensions
        - Demos
        - Tools
        - Compliant terminals
        - Training
        - Development
  - type: input
    attributes:
      label: Other resources
      placeholder: R1, R2, etc.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        <br>

        ## Short description
  - type: input
    attributes:
      label: Short description (sentence 1)
    validations:
      required: true
  - type: input
    attributes:
      label: Short description (sentence 2, optional)
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        <br>

        ## Full description
  - type: input
    attributes:
      label: External page URL
    validations:
      required: false
  - type: textarea
    attributes:
      label: or rich text description
    validations:
      required: false
