name: 📌 External Resource Proposal
description: Fill out this form to provide information about the external resource to be referenced
title: "External Resource Proposal"
labels: ["resource"]
body:
  - type: markdown
    attributes:
      value: |
        ## Supplier name
  - type: input
    attributes:
      label: The name of the company that provides the resource
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Resources types
  - type: checkboxes
    attributes:
      label: Select the types of products or services you are proposing (multiple options can be selected)
      options:
        - label: Reader plugin
          required: false
        - label: Card extension
          required: false
        - label: Demo
          required: false
        - label: Compliant terminal
          required: false
        - label: Training
          required: false
        - label: Development
          required: false
  - type: input
    attributes:
      label: Other resources
      placeholder: R1, R2, etc.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Summary
  - type: input
    attributes:
      label: sentence 1
    validations:
      required: true
  - type: input
    attributes:
      label: sentence 2 (optional)
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Description
  - type: input
    attributes:
      label: External page URL
    validations:
      required: false
  - type: textarea
    attributes:
      label: or rich text description
    validations:
      required: false
