name: 📌 External Resource Proposal
description: Fill out this form to provide information about the external resource to be referenced
title: "External Resource Proposal"
labels: ["resource"]
body:
  - type: input
    attributes:
      label: Supplier name
      placeholder: The name of the company that provides the resource.
      description: The name of the company that provides the resource.
    validations:
      required: true
  - type: input
    attributes:
      label: Company website
      description: Provide the company's website URL.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Types of resources provided
      description: Select the types of products or services you are proposing (multiple options can be selected).
      options:
        - label: Reader plugin
          required: false
        - label: Card extension
          required: false
        - label: Demo
          required: false
        - label: Compliant terminal
          required: false
        - label: Training
          required: false
        - label: Development
          required: false
  - type: input
    attributes:
      label: Other
      description: Non-listed resource, comma separated if multiple.
    validations:
      required: true
  - type: input
    attributes:
      label: Resource Name
      description: Provide a clear and concise name for the resource.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Resource Description
      description: Provide a clear and concise description of the resource and its purpose.
    validations:
      required: true
  - type: input
    attributes:
      label: Resource Link
      description: Provide the URL to the resource.
    validations:
      required: false